# Generated by Django 4.1.5 on 2023-05-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropName', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=25)),
                ('temp', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
            ],
        ),
    ]
