# Generated by Django 4.1.5 on 2023-05-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_measurements_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water_used',
            old_name='t1',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='water_used',
            name='t2',
        ),
    ]
