# Generated by Django 4.1.5 on 2023-05-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notificatios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_farm_name', to='home.farm')),
            ],
        ),
        migrations.DeleteModel(
            name='Notificatios',
        ),
    ]
