# Generated by Django 4.1.5 on 2023-05-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_notifications_delete_notificatios'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
